# Secure Enhanced Caching Configuration Template
# Fixed shell injection vulnerabilities by using environment variables

name: Secure Cache Configuration

on:
  workflow_call:
    inputs:
      cache-type:
        description: 'Type of cache to configure (python, node, mixed)'
        required: true
        type: string
      cache-key-prefix:
        description: 'Prefix for cache keys'
        required: false
        type: string
        default: 'default'
      enable-fallback:
        description: 'Enable fallback cache restoration'
        required: false
        type: boolean
        default: true
      cache-compression:
        description: 'Enable cache compression'
        required: false
        type: boolean
        default: true

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    outputs:
      python-cache-key: ${{ steps.python-cache.outputs.cache-key }}
      node-cache-key: ${{ steps.node-cache.outputs.cache-key }}
      mixed-cache-key: ${{ steps.mixed-cache.outputs.cache-key }}
    
    steps:
      # Python Cache Configuration with security fix
      - name: Configure Python Cache
        if: inputs.cache-type == 'python' || inputs.cache-type == 'mixed'
        id: python-cache
        env:
          CACHE_PREFIX: ${{ inputs.cache-key-prefix }}
        run: |
          # Use environment variable to prevent shell injection
          PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
          REQUIREMENTS_HASH=$(find . -name "requirements*.txt" -exec sha256sum {} \; | sha256sum | cut -d' ' -f1)
          CACHE_KEY="${CACHE_PREFIX}-python-${PYTHON_VERSION}-${REQUIREMENTS_HASH}"
          echo "cache-key=${CACHE_KEY}" >> $GITHUB_OUTPUT
          echo "Python cache key: ${CACHE_KEY}"

      # Node.js Cache Configuration with security fix
      - name: Configure Node.js Cache
        if: inputs.cache-type == 'node' || inputs.cache-type == 'mixed'
        id: node-cache
        env:
          CACHE_PREFIX: ${{ inputs.cache-key-prefix }}
        run: |
          # Use environment variable to prevent shell injection
          NODE_VERSION=$(node --version)
          PACKAGE_LOCK_HASH=$(find . -name "package-lock.json" -exec sha256sum {} \; | sha256sum | cut -d' ' -f1)
          CACHE_KEY="${CACHE_PREFIX}-node-${NODE_VERSION}-${PACKAGE_LOCK_HASH}"
          echo "cache-key=${CACHE_KEY}" >> $GITHUB_OUTPUT
          echo "Node.js cache key: ${CACHE_KEY}"

      # Mixed Cache Configuration with security fix
      - name: Configure Mixed Cache
        if: inputs.cache-type == 'mixed'
        id: mixed-cache
        env:
          CACHE_PREFIX: ${{ inputs.cache-key-prefix }}
          PYTHON_KEY: ${{ steps.python-cache.outputs.cache-key }}
          NODE_KEY: ${{ steps.node-cache.outputs.cache-key }}
        run: |
          # Use environment variables to prevent shell injection
          COMBINED_HASH=$(echo "${PYTHON_KEY}${NODE_KEY}" | sha256sum | cut -d' ' -f1)
          CACHE_KEY="${CACHE_PREFIX}-mixed-${COMBINED_HASH}"
          echo "cache-key=${CACHE_KEY}" >> $GITHUB_OUTPUT
          echo "Mixed cache key: ${CACHE_KEY}"